# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: ""
title_separator: "-"
subtitle: # site tagline that appears below site title in masthead
name: "Jenna Jordan"
description: "All about me - projects, education, thoughts, and more... from a data librarian."
url: "https://jennajordan.me"
baseurl: ""
repository: "jenna-jordan/jenna-jordan.github.io"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute: 200
comments:
  provider: "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname: "https-jenna-jordan-github-io" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
    issue_term: # "pathname" (default)
  giscus:
    repo_id: # Shown during giscus setup at https://giscus.app
    category_name: # Full text name of the category
    category_id: # Shown during giscus setup at https://giscus.app
    discussion_term: # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: # '1' for enabled (default), '0' for disabled
    theme: # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch: # "master"
    endpoint: # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey:
  secret:
atom_feed:
  path: # blank (default) uses feed.xml
  hide: # true, false (default)
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: # lunr (default), algolia, google
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
# SEO Related
google_site_verification:
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username: "JennaJrdn"
facebook:
  username:
  app_id:
  publisher:
og_image: /assets/images/home_splash_main.jpg
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-126687631-1"
    anonymize_ip: # true, false (default)

# Site Author
author:
  name: "Jenna Jordan"
  avatar: "/assets/images/bio_photo.jpg"
  bio: "Data Librarian"
  location: "East Coast, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jenna.jrdn@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JennaJrdn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/jenna-jordan"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/jennajrdn"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jennajordan1"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0001-9246-5355"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jennajrdnknits"
    - label: "Ravelry"
      icon: "fab fa-fw fa-ravelry"
      url: "https://www.ravelry.com/people/JennaJrdn"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JennaJrdn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/jenna-jordan"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/jennajrdn"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jennajrdnknits"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# Collections
collections:
  international-relations-database:
    output: true
    permalink: /:collection/:path/
  prisoners-dilemma:
    output: true
    permalink: /:collection/:path/
  beepocalypse:
    output: true
    permalink: /:collection/:path/
  tidy-pandas-cookbook:
    output: true
    permalink: /:collection/:path/
  carpentries:
    output: true
    permalink: /:collection/:path/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# force Github API metadata for local env
github: [metadata]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _international-relations-database (project)
  - scope:
      path: ""
      type: international-relations-database
    values:
      layout: single
      author_profile: false
      share: true
  # _prisoners-dilemma (project)
  - scope:
      path: ""
      type: prisoners-dilemma
    values:
      layout: single
      author_profile: false
      share: true
  # _beepocalypse (project)
  - scope:
      path: ""
      type: beepocalypse
    values:
      layout: single
      author_profile: false
      share: true
  # _tidy-pandas-cookbook (project)
  - scope:
      path: ""
      type: tidy-pandas-cookbook
    values:
      layout: single
      author_profile: false
      share: true
  # _carpentries (project)
  - scope:
      path: ""
      type: carpentries
    values:
      layout: single
      author_profile: false
      share: true
